### ISSUE TITLE
GitHub set-output deprecation warnings

### ISSUE THREAD

**Issue by jared-rowe** [WyriHaximus/github-action-next-semvers#53]
```
Run WyriHaximus/github-action-next-semvers@v1
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Already updated in `WyriHaximus/github-action-get-previous-tag` that we also use. Much appreciated if you get the chance to sort this one too 🙌

**Comment by dargmuesli** [comment]
@WyriHaximus just a quick note: there are about 5 months left for `set-output` to be replaced before they are fully disabled. I'll try to code a fix, but I'm not fluent in PHP currently. Maybe use it as a starting point.

**Comment by WyriHaximus** [comment]
@dargmuesli Not too worried about the 5 months left to be honest. Aiming to have all my actions updated before the end of the year.
